name: facemap
channels:
  - conda-forge
dependencies:
  - python>3.5
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - scipy
  - pyqt
  - pip:
    - pyqtgraph==0.11.0rc0
    - natsort
    - opencv_python_headless